### ISSUE TITLE
"Maximum call stack size exceeded" in big project with many circular dependencies

### ISSUE THREAD

**Issue by TheBlue-1** [He110te4m/vscode-circular-dependency#14]
## Problem
The circular dependencies are not displayed as errors.
A "Maximum call stack size exceeded" error is displayed in the Extension Host output.

## What might have caused it 
I tried the extension in a small project where it worked perfectly, but then also in a bigger project with some deep circular dependencies. Maybe the project has to many files that get imported with recursion. I think there are also some imports that can't be resolved because of aliases to other packages.

## Stacktrace
```
2023-03-29 10:25:21.650 [error] [he110te4m.vscode-circular-dependency] provider FAILED
2023-03-29 10:25:21.651 [error] RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at Xr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1897)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1692)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
    at Zr (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1710)
    at ae (c:\Users\Arbeit\.vscode\extensions\he110te4m.vscode-circular-dependency-1.4.0\out\extension.js:11:1569)
```

**Comment by He110te4m** [comment]
Yes, there are performance issues in large projects.

If this is a cross-project situation, maybe we need a new `excludes` option to exclude they.

In fact, there is an internal logic that ignores the packages in `node_modules`. This can be done with just a few modifications. I will also update the related examples in `README` synchronously.

Perhaps the extension also needs a depth option to control the depth of recursion.

This part of the processing I will think about, and the subsequent version of the update in the implementation.
